### ISSUE TITLE
Header Layout

### ISSUE THREAD

**Issue by DerStimmler** [co-IT/homepage#161]
1. Um das Logo und Hambuger-Icon befindet sich links und rechts ein Padding, was dazu führt, dass sich beide Elemente beim Öffnen und Schließen des Menüs hin und her bewegen.
Dies ließe sich lösen, indem das Padding einfach herausgenommen wird. Dann sind die Abstände zum Seitenrand auch konsistent mit dem Container des Hauptteils.

2. Die Höhe des Headers ist aktuell auf 90vh eingestellt. Dadurch befindet sich auf meinem 24" Monitor unter dem Bild einfach ein weißer Streifen. Dadurch wirkt es, als wenn die Seite ein wenig kaputt ist.
![image](https://user-images.githubusercontent.com/43130816/219309617-cc641f2b-f29c-48dc-9e22-ba6c918dddc1.png)
Hier habe ich 2 Alternative Vorschläge: Man könnte den Header mit 100vh Fullscreen machen und am unteren Bildschirmrand einen Scroll-Indikator einbauen, damit der Benutzer weiß, dass es nach unten hin noch weiter geht.
![image](https://user-images.githubusercontent.com/43130816/219311499-b422b564-3779-489a-b51e-c81ee818fdd7.png)
Oder man verringert die Höhe auf z.B. nur 60vh, sodass auf jeden Fall immer der folgende Content zu sehen ist.
![image](https://user-images.githubusercontent.com/43130816/219312008-6c6f8150-df2a-45bd-b791-7db26baaccc4.png)

3. Auf den Unterseiten finde ich den Header zu groß, dafür, dass nur 2 Zeilen Text enthalten sind. Es ist zwar cool, dass man so das Bild gut sehen kann, da der Fokus meiner Meinung nach aber eher auf dem Inhalt der Seite liegen sollte, ist der riesen ungenutzte Platz zu viel.
Hier könnte man die Höhe z.B. auf ca. 40vh verringern. Damit das Hintergrundbild dann nicht ungünstig abgeschnitten wird kann man mit `background-size` und `background-position` herumspielen.
In diesem Beispiel z.B.:
```
background-size: cover;
background-position: center 20%;
```
![image](https://user-images.githubusercontent.com/43130816/219315396-6d93c069-4d8c-4095-b59d-45831ea7497e.png)

4. In jedem Fall würde ich den Text im Header vertikal zentrieren. Das wirkt finde ich stimmiger und verringert wie oben erwähnt ungenutzte große Flächen.
Außerdem finde ich, dass man den Text auch ohne Text-Shadow gut lesen kann.

5. Mobil könnte man finde ich auch den Text innerhalb des Bildes anzeigen. Der statische blaue Block passt da finde ich nicht.
![image](https://user-images.githubusercontent.com/43130816/219318828-16bfdafa-8474-41b4-af94-60f11ccfb1f8.png)
Ggf. hier auch mit der `background-position` spielen.

6. Auf der Kontaktseite fehlt ein Bild
![image](https://user-images.githubusercontent.com/43130816/219319044-e5e83550-32d7-468c-980d-67efbd956d84.png)

**Comment by GregOnNet** [comment]
@DerStimmler  Die legal pages und Kontakt aufnehmen haben kein Bild.
Die sollten aber auch nicht so hoch sein.

Die header-höhe habe ich angepasst: #168

**Comment by GregOnNet** [comment]
Closing this issue since it is covered by #175
