### ISSUE TITLE
Menü Layout

### ISSUE THREAD

**Issue by DerStimmler** [co-IT/homepage#163]
1. Im Menü sollte der Abstand unten verringert werden. Hier ist ein Padding von 6rem eingestellt. Bestenfalls ist das padding hier oben und unten gleich. Z.B.:
![image](https://user-images.githubusercontent.com/43130816/219329363-f9e03f8c-0133-478b-b85d-cd81bd4d3b27.png)
2. Wenn man beim Schließen-Button das Icon und Label vertauscht, befindet sich das Icon genau an der Stelle, wo sich das Hamburger Icon befindet. Das sieht beim Öffnen und Schließen des Menüs ruhiger aus.
![image](https://user-images.githubusercontent.com/43130816/219330876-0b89ddad-8795-4b34-9541-ff77d9afb4d4.png)
3. Es gibt einen Breakpoint bei dem das Menü weder per Hamburger-Button, noch per Floating Button erreichbar ist.
![image](https://user-images.githubusercontent.com/43130816/219331191-105a138b-b3e7-4bc6-8ea8-4e786c6168b1.png)
4. Mobil ist das Menü nicht immer Fullscreen
![image](https://user-images.githubusercontent.com/43130816/219337306-bcc9ad2e-2903-4081-8936-0c0b38bafc13.png)
6. Wenn das Menü Mobil Fullscreen ist, kann man weiterhin scrollen. Ich denke das sollte solange deaktiviert sein. Falls man scrollt kann auf dem Smartphone z.B. die Tableiste verschwinden. Dadurch ist das Menü dann auch nicht mehr Fullscreen. Hier hilft evtl. die neue Einheit `dvh`: https://i.stack.imgur.com/plYwy.png
![image](https://user-images.githubusercontent.com/43130816/219337715-fcc20e8d-b4e9-4214-a456-f9ddf30f75d0.png)
7. Es gibt einen Breakpoint, bei der das Menü 2 Schließen-Buttons hat
![image](https://user-images.githubusercontent.com/43130816/219386505-c17eaa46-a1ba-4419-b193-62128d5df089.png)
8. Der Schließen Button im mobilen Menü hat beim hover/focus kein `cursor: pointer;` gesetzt.

**Comment by GregOnNet** [comment]
Hi @DerStimmler , danke für das Feedback.

Wir planen eine neue Navigation mit mehreren Ebenen.
Da wird sich auch grundlegend am Design etwas ändern, weil wir mit den Farbabstufungen nicht 100%ig zu Frieden sind.

Daher schließe ich dieses Issue vorerst.
