### ISSUE TITLE
Interne Seitenlinks in Markdown führen zu kompletten Page-Reload

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/homepage#53]
In einem relativ langen Thread wird diskutiert, wie man die Links von ngx-markdown so umbiegt, dass sie den Angular-Router verwenden, wenn es interne App links sind.

https://github.com/jfcere/ngx-markdown/issues/125#issuecomment-891057098

**Comment by DerStimmler** [comment]
Alle vorgeschlagenen Lösungen sind nicht wirklich optimal meiner Meinung nach. Entweder wir investieren hier Zeit und versuchen selbst noch eine Lösung zu finden, oder wir warten auf einen Fix in der Library.
